name: Trigger auto deployment for container-app-4b5yl555bremc

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-4b5yl555bremc-AutoDeployTrigger-0d77be87-44b7-4eb2-9bec-21b98110ceac.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP4B5YL555BREMC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP4B5YL555BREMC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP4B5YL555BREMC_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistry4b5yl555bremc.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP4B5YL555BREMC_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP4B5YL555BREMC_REGISTRY_PASSWORD }}
          containerAppName: container-app-4b5yl555bremc
          resourceGroup: dockerswarmvisualizera146
          imageToBuild: containerregistry4b5yl555bremc.azurecr.io/container-app-4b5yl555bremc:${{ github.sha }}
          dockerfilePath: Dockerfile


